// Generated by scripts/build-tokens.py from tokens/tokens.json. Do not edit. AnixOps Design 1.0.0.
//! AnixOps design tokens for Rust: egui apps, ratatui TUIs and CLIs. Dependency free;
//! copy this file into your crate (for example `src/anixops_tokens.rs`).
//!
//! egui: `egui::Color32::from_rgba_unmultiplied(c.r, c.g, c.b, c.a)`.
//! ratatui: `Color::Rgb(c.r, c.g, c.b)` or `Color::Indexed(term::ACCENT.ansi256_dark)`.
#![allow(dead_code)]

pub const VERSION: &str = "1.0.0";

/// An sRGB colour with straight (unpremultiplied) alpha.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct Rgba {
    pub r: u8,
    pub g: u8,
    pub b: u8,
    pub a: u8,
}

impl Rgba {
    pub const fn new(r: u8, g: u8, b: u8, a: u8) -> Self {
        Self { r, g, b, a }
    }
}

/// A terminal colour: truecolor for light and dark backgrounds, xterm-256 fallbacks,
/// and the basic ANSI index (0-15) that the user's terminal theme remaps.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct TermColor {
    pub light: Rgba,
    pub dark: Rgba,
    pub ansi256_light: u8,
    pub ansi256_dark: u8,
    pub ansi16: u8,
}

/// UI colours, light theme.
pub mod light {
    use super::Rgba;
    pub const BG: Rgba = Rgba::new(0xFB, 0xFB, 0xFD, 0xFF);
    pub const BG_ELEVATED: Rgba = Rgba::new(0xFF, 0xFF, 0xFF, 0xFF);
    pub const BG_GROUPED: Rgba = Rgba::new(0xF5, 0xF5, 0xF7, 0xFF);
    pub const FILL_1: Rgba = Rgba::new(0x78, 0x78, 0x80, 0x14);
    pub const FILL_2: Rgba = Rgba::new(0x78, 0x78, 0x80, 0x1F);
    pub const FILL_3: Rgba = Rgba::new(0x78, 0x78, 0x80, 0x29);
    pub const SEPARATOR: Rgba = Rgba::new(0x3C, 0x3C, 0x43, 0x1F);
    pub const SEPARATOR_STRONG: Rgba = Rgba::new(0x3C, 0x3C, 0x43, 0x4A);
    pub const MATERIAL: Rgba = Rgba::new(0xFB, 0xFB, 0xFD, 0xB8);
    pub const MATERIAL_SIDEBAR: Rgba = Rgba::new(0xF2, 0xF2, 0xF5, 0xC7);
    pub const LABEL_1: Rgba = Rgba::new(0x1D, 0x1D, 0x1F, 0xFF);
    pub const LABEL_2: Rgba = Rgba::new(0x6E, 0x6E, 0x73, 0xFF);
    pub const LABEL_3: Rgba = Rgba::new(0x86, 0x86, 0x8B, 0xFF);
    pub const ACCENT: Rgba = Rgba::new(0x4F, 0x5B, 0xE8, 0xFF);
    pub const ACCENT_HOVER: Rgba = Rgba::new(0x43, 0x50, 0xDD, 0xFF);
    pub const ACCENT_FILL: Rgba = Rgba::new(0x4F, 0x5B, 0xE8, 0xFF);
    pub const ACCENT_FILL_HOVER: Rgba = Rgba::new(0x43, 0x50, 0xDD, 0xFF);
    pub const ON_ACCENT: Rgba = Rgba::new(0xFF, 0xFF, 0xFF, 0xFF);
    pub const ACCENT_SOFT: Rgba = Rgba::new(0x4F, 0x5B, 0xE8, 0x1A);
    pub const SUCCESS: Rgba = Rgba::new(0x1A, 0x7F, 0x37, 0xFF);
    pub const SUCCESS_SOFT: Rgba = Rgba::new(0x1A, 0x7F, 0x37, 0x1A);
    pub const WARNING: Rgba = Rgba::new(0xB2, 0x50, 0x00, 0xFF);
    pub const WARNING_SOFT: Rgba = Rgba::new(0xB2, 0x50, 0x00, 0x1A);
    pub const DANGER: Rgba = Rgba::new(0xD7, 0x00, 0x15, 0xFF);
    pub const DANGER_FILL: Rgba = Rgba::new(0xD7, 0x00, 0x15, 0xFF);
    pub const DANGER_FILL_HOVER: Rgba = Rgba::new(0xB8, 0x00, 0x0F, 0xFF);
    pub const DANGER_SOFT: Rgba = Rgba::new(0xD7, 0x00, 0x15, 0x14);
    pub const ON_DANGER: Rgba = Rgba::new(0xFF, 0xFF, 0xFF, 0xFF);
    pub const INFO: Rgba = Rgba::new(0x4F, 0x5B, 0xE8, 0xFF);
    pub const CHART_1: Rgba = Rgba::new(0x4F, 0x5B, 0xE8, 0xFF);
    pub const CHART_2: Rgba = Rgba::new(0x08, 0x91, 0xB2, 0xFF);
    pub const CHART_3: Rgba = Rgba::new(0x8B, 0x5C, 0xF6, 0xFF);
    pub const CHART_4: Rgba = Rgba::new(0xDB, 0x27, 0x77, 0xFF);
    pub const CHART_5: Rgba = Rgba::new(0xEA, 0x58, 0x0C, 0xFF);
    pub const CHART_6: Rgba = Rgba::new(0xA1, 0x62, 0x07, 0xFF);
    pub const CHART_7: Rgba = Rgba::new(0x16, 0xA3, 0x4A, 0xFF);
    pub const CHART_8: Rgba = Rgba::new(0x8E, 0x8E, 0x93, 0xFF);
    pub const SHADOW_COLOR: Rgba = Rgba::new(0x00, 0x00, 0x00, 0x0F);
    pub const HIGHLIGHT: Rgba = Rgba::new(0xFF, 0xFF, 0xFF, 0x00);
}

/// UI colours, dark theme.
pub mod dark {
    use super::Rgba;
    pub const BG: Rgba = Rgba::new(0x00, 0x00, 0x00, 0xFF);
    pub const BG_ELEVATED: Rgba = Rgba::new(0x1C, 0x1C, 0x1E, 0xFF);
    pub const BG_GROUPED: Rgba = Rgba::new(0x11, 0x11, 0x13, 0xFF);
    pub const FILL_1: Rgba = Rgba::new(0x78, 0x78, 0x80, 0x29);
    pub const FILL_2: Rgba = Rgba::new(0x78, 0x78, 0x80, 0x3D);
    pub const FILL_3: Rgba = Rgba::new(0x78, 0x78, 0x80, 0x52);
    pub const SEPARATOR: Rgba = Rgba::new(0x54, 0x54, 0x58, 0x7A);
    pub const SEPARATOR_STRONG: Rgba = Rgba::new(0x54, 0x54, 0x58, 0xCC);
    pub const MATERIAL: Rgba = Rgba::new(0x00, 0x00, 0x00, 0xAD);
    pub const MATERIAL_SIDEBAR: Rgba = Rgba::new(0x1C, 0x1C, 0x1E, 0xB8);
    pub const LABEL_1: Rgba = Rgba::new(0xF5, 0xF5, 0xF7, 0xFF);
    pub const LABEL_2: Rgba = Rgba::new(0xA1, 0xA1, 0xA6, 0xFF);
    pub const LABEL_3: Rgba = Rgba::new(0x8E, 0x8E, 0x93, 0xFF);
    pub const ACCENT: Rgba = Rgba::new(0x81, 0x8C, 0xF8, 0xFF);
    pub const ACCENT_HOVER: Rgba = Rgba::new(0x94, 0x9E, 0xFA, 0xFF);
    pub const ACCENT_FILL: Rgba = Rgba::new(0x5B, 0x63, 0xE6, 0xFF);
    pub const ACCENT_FILL_HOVER: Rgba = Rgba::new(0x50, 0x58, 0xDC, 0xFF);
    pub const ON_ACCENT: Rgba = Rgba::new(0xFF, 0xFF, 0xFF, 0xFF);
    pub const ACCENT_SOFT: Rgba = Rgba::new(0x81, 0x8C, 0xF8, 0x2E);
    pub const SUCCESS: Rgba = Rgba::new(0x30, 0xD1, 0x58, 0xFF);
    pub const SUCCESS_SOFT: Rgba = Rgba::new(0x30, 0xD1, 0x58, 0x29);
    pub const WARNING: Rgba = Rgba::new(0xFF, 0x9F, 0x0A, 0xFF);
    pub const WARNING_SOFT: Rgba = Rgba::new(0xFF, 0x9F, 0x0A, 0x29);
    pub const DANGER: Rgba = Rgba::new(0xFF, 0x45, 0x3A, 0xFF);
    pub const DANGER_FILL: Rgba = Rgba::new(0xE0, 0x24, 0x2F, 0xFF);
    pub const DANGER_FILL_HOVER: Rgba = Rgba::new(0xC8, 0x10, 0x2E, 0xFF);
    pub const DANGER_SOFT: Rgba = Rgba::new(0xFF, 0x45, 0x3A, 0x29);
    pub const ON_DANGER: Rgba = Rgba::new(0xFF, 0xFF, 0xFF, 0xFF);
    pub const INFO: Rgba = Rgba::new(0x81, 0x8C, 0xF8, 0xFF);
    pub const CHART_1: Rgba = Rgba::new(0x81, 0x8C, 0xF8, 0xFF);
    pub const CHART_2: Rgba = Rgba::new(0x22, 0xD3, 0xEE, 0xFF);
    pub const CHART_3: Rgba = Rgba::new(0xA7, 0x8B, 0xFA, 0xFF);
    pub const CHART_4: Rgba = Rgba::new(0xF4, 0x72, 0xB6, 0xFF);
    pub const CHART_5: Rgba = Rgba::new(0xFB, 0x92, 0x3C, 0xFF);
    pub const CHART_6: Rgba = Rgba::new(0xFA, 0xCC, 0x15, 0xFF);
    pub const CHART_7: Rgba = Rgba::new(0x4A, 0xDE, 0x80, 0xFF);
    pub const CHART_8: Rgba = Rgba::new(0x8E, 0x8E, 0x93, 0xFF);
    pub const SHADOW_COLOR: Rgba = Rgba::new(0x00, 0x00, 0x00, 0x66);
    pub const HIGHLIGHT: Rgba = Rgba::new(0xFF, 0xFF, 0xFF, 0x0F);
}

/// Brand colours. The gradient is for brand moments only.
pub mod brand {
    use super::Rgba;
    pub const GRADIENT_START: Rgba = Rgba::new(0x38, 0xBD, 0xF8, 0xFF);
    pub const GRADIENT_END: Rgba = Rgba::new(0x63, 0x66, 0xF1, 0xFF);
    pub const PURPLE: Rgba = Rgba::new(0x8B, 0x5C, 0xF6, 0xFF);
    pub const AMBER: Rgba = Rgba::new(0xF5, 0x9E, 0x0B, 0xFF);
    pub const SLATE_900: Rgba = Rgba::new(0x0F, 0x17, 0x2A, 0xFF);
    pub const SLATE_800: Rgba = Rgba::new(0x1E, 0x29, 0x3B, 0xFF);
}

/// Terminal palette. Honour NO_COLOR and never rely on colour alone.
pub mod term {
    use super::{Rgba, TermColor};
    pub const ACCENT: TermColor = TermColor {
        light: Rgba::new(0x4F, 0x5B, 0xE8, 0xFF),
        dark: Rgba::new(0x81, 0x8C, 0xF8, 0xFF),
        ansi256_light: 62,
        ansi256_dark: 105,
        ansi16: 4,
    };
    pub const SUCCESS: TermColor = TermColor {
        light: Rgba::new(0x1A, 0x7F, 0x37, 0xFF),
        dark: Rgba::new(0x30, 0xD1, 0x58, 0xFF),
        ansi256_light: 29,
        ansi256_dark: 41,
        ansi16: 2,
    };
    pub const WARNING: TermColor = TermColor {
        light: Rgba::new(0xB2, 0x50, 0x00, 0xFF),
        dark: Rgba::new(0xFF, 0x9F, 0x0A, 0xFF),
        ansi256_light: 130,
        ansi256_dark: 214,
        ansi16: 3,
    };
    pub const DANGER: TermColor = TermColor {
        light: Rgba::new(0xD7, 0x00, 0x15, 0xFF),
        dark: Rgba::new(0xFF, 0x45, 0x3A, 0xFF),
        ansi256_light: 160,
        ansi256_dark: 203,
        ansi16: 1,
    };
    pub const MUTED: TermColor = TermColor {
        light: Rgba::new(0x6E, 0x6E, 0x73, 0xFF),
        dark: Rgba::new(0x8E, 0x8E, 0x93, 0xFF),
        ansi256_light: 242,
        ansi256_dark: 246,
        ansi16: 8,
    };
    pub const BRAND_START: TermColor = TermColor {
        light: Rgba::new(0x38, 0xBD, 0xF8, 0xFF),
        dark: Rgba::new(0x38, 0xBD, 0xF8, 0xFF),
        ansi256_light: 75,
        ansi256_dark: 75,
        ansi16: 6,
    };
    pub const BRAND_END: TermColor = TermColor {
        light: Rgba::new(0x63, 0x66, 0xF1, 0xFF),
        dark: Rgba::new(0x63, 0x66, 0xF1, 0xFF),
        ansi256_light: 63,
        ansi256_dark: 63,
        ansi16: 5,
    };

    /// Three-line ASCII mark for banners and `--version` output.
    pub const ASCII_MARK: [&str; 3] = [
        "  ___",
        " / o \\",
        " \\___/",
    ];
}

/// Space in logical pixels.
pub mod space {
    pub const S0_5: f32 = 2.0;
    pub const S1: f32 = 4.0;
    pub const S2: f32 = 8.0;
    pub const S3: f32 = 12.0;
    pub const S4: f32 = 16.0;
    pub const S5: f32 = 20.0;
    pub const S6: f32 = 24.0;
    pub const S8: f32 = 32.0;
    pub const S10: f32 = 40.0;
    pub const S12: f32 = 48.0;
    pub const S16: f32 = 64.0;
    pub const S20: f32 = 80.0;
}

/// Radius in logical pixels.
pub mod radius {
    pub const XS: f32 = 6.0;
    pub const SM: f32 = 10.0;
    pub const MD: f32 = 14.0;
    pub const LG: f32 = 20.0;
    pub const PILL: f32 = 980.0;
}

/// Size in logical pixels.
pub mod size {
    pub const CONTROL_LG: f32 = 44.0;
    pub const CONTROL_MD: f32 = 36.0;
    pub const CONTROL_SM: f32 = 28.0;
    pub const CONTENT_USER: f32 = 980.0;
    pub const CONTENT_ADMIN: f32 = 1280.0;
    pub const CONTENT_WIDE: f32 = 1440.0;
    pub const CONTENT_READ: f32 = 692.0;
}

/// Durations in milliseconds.
pub mod duration {
    pub const MICRO: u64 = 120;
    pub const TOGGLE: u64 = 200;
    pub const OVERLAY: u64 = 280;
    pub const PAGE: u64 = 240;
}
