#!/usr/bin/env python3
"""Generate every platform output from tokens/tokens.json.

Dependency free. Run from the repository root:

    python3 scripts/build-tokens.py           # write all outputs
    python3 scripts/build-tokens.py --check   # exit 1 if any output is stale

Outputs:

    tokens/css/tokens.css                  CSS custom properties (light, dark, system)
    tokens/tailwind/preset.cjs             Tailwind CSS v3 preset
    tokens/tailwind/theme.css              Tailwind CSS v4 @theme
    tokens/element-plus/element-plus.css   Element Plus variable overrides
    tokens/flutter/anixops_tokens.dart     Flutter ThemeData, ColorScheme and extension
    tokens/go/anixops/tokens.go            Go: UI colours and terminal palette
    tokens/rust/anixops_tokens.rs          Rust (egui, ratatui): dependency-free constants

CSS theme pattern: bare :root holds light values; dark values apply under
prefers-color-scheme: dark unless data-theme="light" is set, and always under
data-theme="dark".
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "tokens" / "tokens.json"
ASCII_MARK = ROOT / "brand" / "assets" / "ascii-mark.txt"
VERSION = "1.0.2"
HEADER = f"Generated by scripts/build-tokens.py from tokens/tokens.json. Do not edit. AnixOps Design {VERSION}."

DARK_MEDIA = '@media (prefers-color-scheme: dark)'
DARK_AUTO = ':root:not([data-theme="light"])'
DARK_FORCED = ':root[data-theme="dark"]'


# ---------------------------------------------------------------- helpers

def leaves(node, path=()):
    """Yield (path, value) for every token below node."""
    for key, child in node.items():
        if key.startswith("$"):
            continue
        if isinstance(child, dict) and "$value" in child:
            yield path + (key,), child["$value"]
        elif isinstance(child, dict):
            yield from leaves(child, path + (key,))


def values(group):
    """Ordered {name: value} for one flat token group."""
    return {k: v["$value"] for k, v in group.items() if not k.startswith("$")}


def rgba(value):
    """Parse #RRGGBB or rgba(r, g, b, a) into (r, g, b, a) with a in 0..1."""
    if value.startswith("#"):
        h = value[1:]
        return int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16), 1.0
    m = re.fullmatch(r"rgba\(\s*(\d+),\s*(\d+),\s*(\d+),\s*([\d.]+)\s*\)", value)
    if not m:
        raise ValueError(f"unsupported colour {value!r}")
    return int(m[1]), int(m[2]), int(m[3]), float(m[4])


def mix(a, b, weight):
    """Mix hex colour a into hex colour b; weight is the share of b (0..1)."""
    ca, cb = rgba(a), rgba(b)
    return "#" + "".join(f"{round(ca[i] * (1 - weight) + cb[i] * weight):02X}" for i in range(3))


def camel(name):
    head, *rest = re.split(r"[-.]", name)
    return head + "".join(p[:1].upper() + p[1:] for p in rest)


def go_name(prefix, name):
    c = camel(name)
    return prefix + c[:1].upper() + c[1:]


def const_case(name):
    return re.sub(r"[-.]", "_", name).upper()


def px(value):
    return float(value.removesuffix("px"))


def num(value):
    return f"{value:g}"


def css_value(value):
    if isinstance(value, list) and value and all(isinstance(v, (int, float)) for v in value):
        return "cubic-bezier(" + ", ".join(f"{v:g}" for v in value) + ")"
    if isinstance(value, list):
        return ", ".join(f'"{v}"' if " " in v else v for v in value)
    return str(value)


def block(selector, decls, indent=""):
    inner = "\n".join(f"{indent}  {name}: {value};" for name, value in decls)
    return f"{indent}{selector} {{\n{inner}\n{indent}}}"


def themed_css(light, dark, extra_dark=()):
    """Light on :root, dark under the media query and the forced attribute."""
    dark = list(dark) + list(extra_dark)
    return "\n\n".join([
        block(":root", light),
        f"{DARK_MEDIA} {{\n" + block(DARK_AUTO, dark, "  ") + "\n}",
        block(DARK_FORCED, dark),
    ])


# ---------------------------------------------------------------- CSS

def build_css(t):
    common, light, dark, comments = [], [], [], []
    for path, value in leaves(t):
        group = path[0]
        if group == "terminal":
            continue
        if group == "color" and path[1] in ("light", "dark"):
            target = light if path[1] == "light" else dark
            target.append((f"--{'-'.join(path[2:])}", css_value(value)))
        elif group == "color":  # brand
            common.append((f"--brand-{'-'.join(path[2:])}", css_value(value)))
        elif group == "type":
            name = path[1]
            common.append((f"--type-{name}-size", value["fontSize"]))
            common.append((f"--type-{name}-line", f"{value['lineHeight']:g}"))
            common.append((f"--type-{name}-weight", str(value["fontWeight"])))
            common.append((f"--type-{name}-tracking", value["letterSpacing"]))
        elif group == "breakpoint":
            comments.append(f"{path[1]} {value}")
        elif group == "font":
            common.append((f"--font-{path[2]}" if path[1] == "family" else f"--weight-{path[2]}", css_value(value)))
        elif group == "motion":
            common.append((f"--{'ease' if path[1] == 'easing' else 'dur'}-{path[2]}", css_value(value)))
        else:
            common.append((f"--{'-'.join(path)}", css_value(value)))
    common.append(("--brand-gradient", "linear-gradient(135deg, var(--brand-gradient-start), var(--brand-gradient-end))"))
    return "\n".join([
        f"/* {HEADER} */",
        f"/* Breakpoints (use literally in media queries): {', '.join(comments)} */",
        "",
        themed_css(common + light + [("color-scheme", "light")], dark, [("color-scheme", "dark")]),
        "",
        "@media (max-width: 833px) {\n  :root {\n    --type-display-size: 34px;\n    --type-title-1-size: 28px;\n  }\n}",
        "",
    ])


# ---------------------------------------------------------------- Tailwind

def js(value, indent=0):
    """Small JSON-like JS literal writer with stable, readable output."""
    pad = "  " * indent
    if isinstance(value, dict):
        if not value:
            return "{}"
        items = []
        for k, v in value.items():
            key = k if re.fullmatch(r"[A-Za-z_$][\w$]*", k) else json.dumps(k)
            items.append(f"{pad}  {key}: {js(v, indent + 1)},")
        return "{\n" + "\n".join(items) + f"\n{pad}}}"
    if isinstance(value, list):
        return "[" + ", ".join(js(v, indent) for v in value) + "]"
    return json.dumps(value)


def build_tailwind_v3(t):
    c = t["color"]
    colors = {f"brand-{k}": f"var(--brand-{k})" for k in values(c["brand"])}
    colors.update({k: f"var(--{k})" for k in values(c["light"])})
    font_size = {
        name: [f"var(--type-{name}-size)", {
            "lineHeight": f"var(--type-{name}-line)",
            "letterSpacing": f"var(--type-{name}-tracking)",
            "fontWeight": f"var(--type-{name}-weight)",
        }]
        for name in values(t["type"])
    }
    theme = {
        "screens": values(t["breakpoint"]),
        "extend": {
            "colors": colors,
            "backgroundImage": {"brand-gradient": "var(--brand-gradient)"},
            "fontFamily": {"sans": ["var(--font-sans)"], "mono": ["var(--font-mono)"]},
            "fontSize": font_size,
            "borderRadius": {k: f"var(--radius-{k})" for k in values(t["radius"])},
            "boxShadow": {k: f"var(--shadow-{k})" for k in values(t["shadow"])},
            "maxWidth": {k: f"var(--size-{k})" for k in values(t["size"]) if k.startswith("content-")},
            "height": {k: f"var(--size-{k})" for k in values(t["size"]) if k.startswith("control-")},
            "transitionTimingFunction": {k: f"var(--ease-{k})" for k in values(t["motion"]["easing"])},
            "transitionDuration": {k: f"var(--dur-{k})" for k in values(t["motion"]["duration"])},
            "zIndex": {k: f"var(--z-{k})" for k in values(t["z"])},
        },
    }
    return "\n".join([
        f"// {HEADER}",
        "// Tailwind CSS v3 preset. Load tokens/css/tokens.css first; every value is a",
        "// CSS variable, so light and dark switch without `dark:` variants.",
        "// Spacing is not overridden: Tailwind's default scale already matches --space-*.",
        "/** @type {import('tailwindcss').Config} */",
        f"module.exports = {js({'theme': theme})};",
        "",
    ])


def build_tailwind_v4(t):
    c = t["color"]
    color_lines = [f"  --color-brand-{k}: var(--brand-{k});" for k in values(c["brand"])]
    color_lines += [f"  --color-{k}: var(--{k});" for k in values(c["light"])]
    other = []
    for name in values(t["type"]):
        other += [
            f"  --text-{name}: var(--type-{name}-size);",
            f"  --text-{name}--line-height: var(--type-{name}-line);",
            f"  --text-{name}--letter-spacing: var(--type-{name}-tracking);",
            f"  --text-{name}--font-weight: var(--type-{name}-weight);",
        ]
    other += [f"  --container-{k}: var(--size-{k});" for k in values(t["size"]) if k.startswith("content-")]
    # Theme names that tokens.css also defines (--font-*, --radius-*, --shadow-*, --ease-*)
    # get the literal token values: `--x: var(--x)` would be a cycle, and identical values
    # make load order irrelevant.
    literal = [f"  --font-{k}: {css_value(v)};" for k, v in values(t["font"]["family"]).items()]
    literal += [f"  --shadow-{k}: {v};" for k, v in values(t["shadow"]).items()]
    literal += [f"  --ease-{k}: {css_value(v)};" for k, v in values(t["motion"]["easing"]).items()]
    literal += [f"  --radius-{k}: {v};" for k, v in values(t["radius"]).items()]
    literal += [f"  --breakpoint-{k}: {v};" for k, v in values(t["breakpoint"]).items()]
    return "\n".join([
        f"/* {HEADER} */",
        "/* Tailwind CSS v4. Usage:",
        '     @import "tailwindcss";',
        '     @import "<path>/tokens/css/tokens.css";',
        '     @import "<path>/tokens/tailwind/theme.css";',
        "   Colours are CSS variables, so light and dark switch without `dark:` variants. */",
        "",
        "@theme {",
        "  --breakpoint-*: initial;",
        *literal,
        "}",
        "",
        "@theme inline {",
        *color_lines,
        *other,
        "}",
        "",
        "/* v4 has no theme namespace for these; plain utilities instead. */",
        "@utility bg-brand-gradient {\n  background-image: var(--brand-gradient);\n}",
        *[f"@utility duration-{k} {{\n  transition-duration: var(--dur-{k});\n}}" for k in values(t["motion"]["duration"])],
        *[f"@utility z-{k} {{\n  z-index: var(--z-{k});\n}}" for k in values(t["z"])],
        "",
    ])


# ---------------------------------------------------------------- Element Plus

def build_element_plus(t):
    c = t["color"]

    def theme_decls(theme):
        p = values(c[theme])
        base = "#FFFFFF" if theme == "light" else p["bg-elevated"]
        shade = "#000000" if theme == "light" else "#FFFFFF"
        decls = []
        roles = [("primary", p["accent-fill"]), ("success", p["success"]), ("warning", p["warning"]),
                 ("danger", p["danger"]), ("error", p["danger"]), ("info", p["label-2"])]
        for role, colour in roles:
            decls.append((f"--el-color-{role}", colour))
            for step in (3, 5, 7, 8, 9):
                decls.append((f"--el-color-{role}-light-{step}", mix(colour, base, step / 10)))
            decls.append((f"--el-color-{role}-dark-2", mix(colour, shade, 0.2)))
        return decls

    shared = [
        ("--el-bg-color", "var(--bg-elevated)"),
        ("--el-bg-color-page", "var(--bg)"),
        ("--el-bg-color-overlay", "var(--bg-elevated)"),
        ("--el-text-color-primary", "var(--label-1)"),
        ("--el-text-color-regular", "var(--label-1)"),
        ("--el-text-color-secondary", "var(--label-2)"),
        ("--el-text-color-placeholder", "var(--label-3)"),
        ("--el-text-color-disabled", "var(--label-3)"),
        ("--el-border-color", "var(--separator-strong)"),
        ("--el-border-color-light", "var(--separator)"),
        ("--el-border-color-lighter", "var(--separator)"),
        ("--el-border-color-extra-light", "var(--separator)"),
        ("--el-border-color-dark", "var(--separator-strong)"),
        ("--el-border-color-darker", "var(--separator-strong)"),
        ("--el-fill-color", "var(--fill-1)"),
        ("--el-fill-color-light", "var(--fill-1)"),
        ("--el-fill-color-lighter", "var(--fill-1)"),
        ("--el-fill-color-extra-light", "var(--fill-1)"),
        ("--el-fill-color-dark", "var(--fill-2)"),
        ("--el-fill-color-darker", "var(--fill-3)"),
        ("--el-fill-color-blank", "var(--bg-elevated)"),
        ("--el-box-shadow", "var(--shadow-2)"),
        ("--el-box-shadow-light", "var(--shadow-1)"),
        ("--el-box-shadow-lighter", "var(--shadow-1)"),
        ("--el-box-shadow-dark", "var(--shadow-3)"),
        ("--el-border-radius-base", "var(--radius-xs)"),
        ("--el-border-radius-small", "var(--radius-xs)"),
        ("--el-border-radius-round", "var(--radius-pill)"),
        ("--el-font-family", "var(--font-sans)"),
        ("--el-transition-function-ease-in-out-bezier", "var(--ease-standard)"),
        ("--el-component-size-large", "var(--size-control-lg)"),
        ("--el-component-size", "var(--size-control-md)"),
        ("--el-component-size-small", "var(--size-control-sm)"),
    ]
    return "\n".join([
        f"/* {HEADER} */",
        "/* Element Plus overrides. Load after element-plus/dist/index.css and after",
        "   tokens/css/tokens.css. Do not also load Element Plus's dark CSS or set html.dark:",
        "   these variables follow the system theme and data-theme like tokens.css.",
        "   Primary light-N/dark-2 steps are mixed with the card colour at build time. */",
        "",
        themed_css(shared + theme_decls("light"), theme_decls("dark")),
        "",
    ])


# ---------------------------------------------------------------- Flutter

def dart_color(value):
    r, g, b, a = rgba(value)
    return f"Color(0x{round(a * 255):02X}{r:02X}{g:02X}{b:02X})"


def build_flutter(t):
    c = t["color"]
    names = list(values(c["light"]))
    fields = [camel(n) for n in names]
    out = [
        f"// {HEADER}",
        "//",
        "// Usage:",
        "//   MaterialApp(theme: anixOpsTheme(Brightness.light), darkTheme: anixOpsTheme(Brightness.dark))",
        "//   final c = Theme.of(context).extension<AnixOpsColors>()!;  // c.label2, c.success, ...",
        "//",
        "// Inter is not bundled here: add fonts/inter (or google_fonts) to pubspec.yaml, or pass",
        "// fontFamily: null to use the platform font.",
        "",
        "// ignore_for_file: constant_identifier_names, non_constant_identifier_names",
        "import 'package:flutter/material.dart';",
        "",
        "/// AnixOps colour tokens for one theme. Read with",
        "/// `Theme.of(context).extension<AnixOpsColors>()!`.",
        "@immutable",
        "class AnixOpsColors extends ThemeExtension<AnixOpsColors> {",
        "  const AnixOpsColors({",
        *[f"    required this.{f}," for f in fields],
        "  });",
        "",
        *[f"  final Color {f};" for f in fields],
        "",
    ]
    for theme in ("light", "dark"):
        p = values(c[theme])
        out += [f"  static const {theme} = AnixOpsColors("]
        out += [f"    {camel(n)}: {dart_color(p[n])}," for n in names]
        out += ["  );", ""]
    out += [
        "  @override",
        "  AnixOpsColors copyWith({" + ", ".join(f"Color? {f}" for f in fields) + "}) {",
        "    return AnixOpsColors(",
        *[f"      {f}: {f} ?? this.{f}," for f in fields],
        "    );",
        "  }",
        "",
        "  @override",
        "  AnixOpsColors lerp(ThemeExtension<AnixOpsColors>? other, double t) {",
        "    if (other is! AnixOpsColors) return this;",
        "    return AnixOpsColors(",
        *[f"      {f}: Color.lerp({f}, other.{f}, t)!," for f in fields],
        "    );",
        "  }",
        "}",
        "",
        "/// Brand colours. The gradient is for brand moments only (logo tile, login, hero).",
        "abstract final class AnixOpsBrand {",
        *[f"  static const {camel(k)} = {dart_color(v)};" for k, v in values(c["brand"]).items()],
        "  static const gradient = LinearGradient(",
        "    begin: Alignment.topLeft,",
        "    end: Alignment.bottomRight,",
        "    colors: [gradientStart, gradientEnd],",
        "  );",
        "}",
        "",
        "abstract final class AnixOpsSpace {",
        *[f"  static const double s{k.replace('-', '_')} = {num(px(v))};" for k, v in values(t["space"]).items()],
        "}",
        "",
        "abstract final class AnixOpsRadius {",
        *[f"  static const double {camel(k)} = {num(px(v))};" for k, v in values(t["radius"]).items()],
        "}",
        "",
        "abstract final class AnixOpsSize {",
        *[f"  static const double {camel(k)} = {num(px(v))};" for k, v in values(t["size"]).items()],
        "}",
        "",
        "abstract final class AnixOpsMotion {",
        *[f"  static const {camel(k)} = Duration(milliseconds: {int(v.removesuffix('ms'))});"
          for k, v in values(t["motion"]["duration"]).items()],
        *[f"  static const {camel(k)} = Cubic({', '.join(num(x) for x in v)});"
          for k, v in values(t["motion"]["easing"]).items()],
        "}",
        "",
        "/// The seven-step type scale. Colours come from the theme.",
        "abstract final class AnixOpsType {",
    ]
    for name, v in values(t["type"]).items():
        size = px(v["fontSize"])
        tracking = float(v["letterSpacing"].removesuffix("em") or 0) * size
        out.append(
            f"  static const {camel(name)} = TextStyle(fontSize: {num(size)}, height: {num(v['lineHeight'])}, "
            f"fontWeight: FontWeight.w{v['fontWeight']}, letterSpacing: {round(tracking, 3):g});")
    out += [
        "}",
        "",
        "/// Material 3 theme built from the tokens.",
        "ThemeData anixOpsTheme(Brightness brightness, {String? fontFamily = 'Inter'}) {",
        "  final c = brightness == Brightness.dark ? AnixOpsColors.dark : AnixOpsColors.light;",
        "  final scheme = ColorScheme(",
        "    brightness: brightness,",
        "    primary: c.accentFill,",
        "    onPrimary: c.onAccent,",
        "    secondary: c.accentFill,",
        "    onSecondary: c.onAccent,",
        "    error: c.dangerFill,",
        "    onError: c.onDanger,",
        "    surface: c.bgElevated,",
        "    onSurface: c.label1,",
        "    onSurfaceVariant: c.label2,",
        "    outline: c.separatorStrong,",
        "    outlineVariant: c.separator,",
        "  );",
        "  const textTheme = TextTheme(",
        "    displayLarge: AnixOpsType.display,",
        "    headlineLarge: AnixOpsType.title1,",
        "    headlineMedium: AnixOpsType.title2,",
        "    titleLarge: AnixOpsType.title3,",
        "    titleMedium: AnixOpsType.body,",
        "    bodyLarge: AnixOpsType.body,",
        "    bodyMedium: AnixOpsType.body,",
        "    bodySmall: AnixOpsType.callout,",
        "    labelLarge: AnixOpsType.callout,",
        "    labelMedium: AnixOpsType.caption,",
        "    labelSmall: AnixOpsType.caption,",
        "  );",
        "  return ThemeData(",
        "    useMaterial3: true,",
        "    brightness: brightness,",
        "    colorScheme: scheme,",
        "    scaffoldBackgroundColor: c.bg,",
        "    dividerColor: c.separator,",
        "    fontFamily: fontFamily,",
        "    fontFamilyFallback: const ['PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei', 'Noto Sans SC'],",
        "    textTheme: textTheme.apply(bodyColor: c.label1, displayColor: c.label1),",
        "    extensions: [c],",
        "  );",
        "}",
        "",
    ]
    return "\n".join(out)


# ---------------------------------------------------------------- Go

def ascii_mark():
    return ASCII_MARK.read_text(encoding="utf-8").rstrip("\n").split("\n")


def go_aligned(rows):
    rows = list(rows)
    width = max(len(name) for name, _ in rows)
    return [f"\t{name:<{width}} = {rhs}" for name, rhs in rows]


def build_go(t):
    c = t["color"]
    light, dark = values(c["light"]), values(c["dark"])
    out = [
        "// Code generated by scripts/build-tokens.py from tokens/tokens.json. DO NOT EDIT.",
        "",
        "package anixops",
        "",
        "// Version is the AnixOps Design version these tokens come from.",
        f'const Version = "{VERSION}"',
        "",
        "// UI colours. Values are CSS colour strings (#RRGGBB or rgba()).",
        "var (",
    ]
    out += go_aligned((go_name("UI", k), f'Color{{Light: "{light[k]}", Dark: "{dark[k]}"}}') for k in light)
    out += [")", "", "// Brand colours (theme independent).", "const ("]
    out += go_aligned((go_name("Brand", k), f'"{v}"') for k, v in values(c["brand"]).items())
    out += [")", "", "// Terminal palette for CLIs and TUIs.", "var ("]
    out += go_aligned(
        (go_name("Term", k),
         f'TermColor{{Light: "{v["light"]["$value"]}", Dark: "{v["dark"]["$value"]}", '
         f'ANSI256Light: {v["ansi256-light"]["$value"]}, ANSI256Dark: {v["ansi256-dark"]["$value"]}, '
         f'ANSI16: {v["ansi16"]["$value"]}}}')
        for k, v in t["terminal"].items() if not k.startswith("$"))
    out += [")", "", "// ASCIIMark is the three-line ASCII mark used in banners and --version output.",
            "var ASCIIMark = [...]string{"]
    out += [f"\t{json.dumps(line)}," for line in ascii_mark()]
    out += ["}", ""]
    return "\n".join(out)


# ---------------------------------------------------------------- Rust

def rust_rgba(value):
    r, g, b, a = rgba(value)
    return f"Rgba::new(0x{r:02X}, 0x{g:02X}, 0x{b:02X}, 0x{round(a * 255):02X})"


def build_rust(t):
    c = t["color"]
    out = [
        f"// {HEADER}",
        "//! AnixOps design tokens for Rust: egui apps, ratatui TUIs and CLIs. Dependency free;",
        "//! copy this file into your crate (for example `src/anixops_tokens.rs`).",
        "//!",
        "//! egui: `egui::Color32::from_rgba_unmultiplied(c.r, c.g, c.b, c.a)`.",
        "//! ratatui: `Color::Rgb(c.r, c.g, c.b)` or `Color::Indexed(term::ACCENT.ansi256_dark)`.",
        "#![allow(dead_code)]",
        "",
        f'pub const VERSION: &str = "{VERSION}";',
        "",
        "/// An sRGB colour with straight (unpremultiplied) alpha.",
        "#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]",
        "pub struct Rgba {",
        "    pub r: u8,",
        "    pub g: u8,",
        "    pub b: u8,",
        "    pub a: u8,",
        "}",
        "",
        "impl Rgba {",
        "    pub const fn new(r: u8, g: u8, b: u8, a: u8) -> Self {",
        "        Self { r, g, b, a }",
        "    }",
        "}",
        "",
        "/// A terminal colour: truecolor for light and dark backgrounds, xterm-256 fallbacks,",
        "/// and the basic ANSI index (0-15) that the user's terminal theme remaps.",
        "#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]",
        "pub struct TermColor {",
        "    pub light: Rgba,",
        "    pub dark: Rgba,",
        "    pub ansi256_light: u8,",
        "    pub ansi256_dark: u8,",
        "    pub ansi16: u8,",
        "}",
        "",
    ]
    for theme in ("light", "dark"):
        out += [f"/// UI colours, {theme} theme.", f"pub mod {theme} {{", "    use super::Rgba;"]
        out += [f"    pub const {const_case(k)}: Rgba = {rust_rgba(v)};" for k, v in values(c[theme]).items()]
        out += ["}", ""]
    out += ["/// Brand colours. The gradient is for brand moments only.", "pub mod brand {", "    use super::Rgba;"]
    out += [f"    pub const {const_case(k)}: Rgba = {rust_rgba(v)};" for k, v in values(c["brand"]).items()]
    out += ["}", "", "/// Terminal palette. Honour NO_COLOR and never rely on colour alone.", "pub mod term {",
            "    use super::{Rgba, TermColor};"]
    for k, v in t["terminal"].items():
        if k.startswith("$"):
            continue
        out += [
            f"    pub const {const_case(k)}: TermColor = TermColor {{",
            f"        light: {rust_rgba(v['light']['$value'])},",
            f"        dark: {rust_rgba(v['dark']['$value'])},",
            f"        ansi256_light: {v['ansi256-light']['$value']},",
            f"        ansi256_dark: {v['ansi256-dark']['$value']},",
            f"        ansi16: {v['ansi16']['$value']},",
            "    };",
        ]
    out += ["", "    /// Three-line ASCII mark for banners and `--version` output.",
            "    pub const ASCII_MARK: [&str; %d] = [" % len(ascii_mark())]
    out += [f"        {json.dumps(line)}," for line in ascii_mark()]
    out += ["    ];", "}", ""]
    for group, unit in (("space", "px"), ("radius", "px"), ("size", "px")):
        out += [f"/// {group.capitalize()} in logical pixels.", f"pub mod {group} {{"]
        out += [f"    pub const {('S' if group == 'space' else '') + const_case(k)}: f32 = {px(v):.1f};"
                for k, v in values(t[group]).items()]
        out += ["}", ""]
    out += ["/// Durations in milliseconds.", "pub mod duration {"]
    out += [f"    pub const {const_case(k)}: u64 = {int(v.removesuffix('ms'))};"
            for k, v in values(t["motion"]["duration"]).items()]
    out += ["}", ""]
    return "\n".join(out)


# ---------------------------------------------------------------- main

OUTPUTS = {
    "tokens/css/tokens.css": build_css,
    "tokens/tailwind/preset.cjs": build_tailwind_v3,
    "tokens/tailwind/theme.css": build_tailwind_v4,
    "tokens/element-plus/element-plus.css": build_element_plus,
    "tokens/flutter/anixops_tokens.dart": build_flutter,
    "tokens/go/anixops/tokens.go": build_go,
    "tokens/rust/anixops_tokens.rs": build_rust,
}


def main():
    tokens = json.loads(SRC.read_text(encoding="utf-8"))
    check = "--check" in sys.argv
    stale = 0
    for rel, builder in OUTPUTS.items():
        path = ROOT / rel
        content = builder(tokens)
        if check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                print(f"{rel} is stale; run scripts/build-tokens.py", file=sys.stderr)
                stale = 1
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"wrote {rel}")
    return stale


if __name__ == "__main__":
    sys.exit(main())
