#!/usr/bin/env python3
"""Generate tokens/css/tokens.css from tokens/tokens.json.

Dependency free. Run from the repository root:

    python3 scripts/build-tokens.py           # write tokens/css/tokens.css
    python3 scripts/build-tokens.py --check   # exit 1 if the file is stale

Theme pattern: bare :root holds light values; dark values apply under
prefers-color-scheme: dark unless data-theme="light" is set, and always under
data-theme="dark".
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "tokens" / "tokens.json"
OUT = ROOT / "tokens" / "css" / "tokens.css"


def leaves(node, path=()):
    """Yield (path, value) for every token below node."""
    for key, child in node.items():
        if key.startswith("$"):
            continue
        if isinstance(child, dict) and "$value" in child:
            yield path + (key,), child["$value"]
        elif isinstance(child, dict):
            yield from leaves(child, path + (key,))


def css_value(value):
    if isinstance(value, list) and value and all(isinstance(v, (int, float)) for v in value):
        return "cubic-bezier(" + ", ".join(f"{v:g}" for v in value) + ")"
    if isinstance(value, list):
        return ", ".join(f'"{v}"' if " " in v else v for v in value)
    return str(value)


def block(selector, decls, indent=""):
    inner = "\n".join(f"{indent}  {name}: {value};" for name, value in decls)
    return f"{indent}{selector} {{\n{inner}\n{indent}}}"


def build(tokens):
    common, light, dark, comments = [], [], [], []
    for path, value in leaves(tokens):
        group = path[0]
        if group == "color" and path[1] in ("light", "dark"):
            target = light if path[1] == "light" else dark
            target.append((f"--{'-'.join(path[2:])}", css_value(value)))
        elif group == "color":  # brand
            common.append((f"--brand-{'-'.join(path[2:])}", css_value(value)))
        elif group == "type":
            name = path[1]
            common.append((f"--type-{name}-size", value["fontSize"]))
            common.append((f"--type-{name}-line", f"{value['lineHeight']:g}"))
            common.append((f"--type-{name}-weight", str(value["fontWeight"])))
            common.append((f"--type-{name}-tracking", value["letterSpacing"]))
        elif group == "breakpoint":
            comments.append(f"{path[1]} {value}")
        elif group == "font":
            common.append((f"--font-{path[2]}" if path[1] == "family" else f"--weight-{path[2]}", css_value(value)))
        elif group == "motion":
            common.append((f"--{'ease' if path[1] == 'easing' else 'dur'}-{path[2]}", css_value(value)))
        else:
            common.append((f"--{'-'.join(path)}", css_value(value)))
    common.append(("--brand-gradient", "linear-gradient(135deg, var(--brand-gradient-start), var(--brand-gradient-end))"))
    dark_decls = dark + [("color-scheme", "dark")]
    parts = [
        "/* Generated by scripts/build-tokens.py from tokens/tokens.json. Do not edit. */",
        "/* AnixOps Design System 1.0.0 DRAFT */",
        f"/* Breakpoints (use literally in media queries): {', '.join(comments)} */",
        "",
        block(":root", common + light + [("color-scheme", "light")]),
        "",
        "@media (prefers-color-scheme: dark) {\n" + block(':root:not([data-theme="light"])', dark_decls, "  ") + "\n}",
        "",
        block(':root[data-theme="dark"]', dark_decls),
        "",
        "@media (max-width: 833px) {\n  :root {\n    --type-display-size: 34px;\n    --type-title-1-size: 28px;\n  }\n}",
        "",
    ]
    return "\n".join(parts)


def main():
    css = build(json.loads(SRC.read_text(encoding="utf-8")))
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != css:
            print(f"{OUT.relative_to(ROOT)} is stale; run scripts/build-tokens.py", file=sys.stderr)
            return 1
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(css, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
