// Code generated by scripts/build-tokens.py from tokens/tokens.json. DO NOT EDIT.

package anixops

// Version is the AnixOps Design version these tokens come from.
const Version = "1.0.0"

// UI colours. Values are CSS colour strings (#RRGGBB or rgba()).
var (
	UIBg              = Color{Light: "#FBFBFD", Dark: "#000000"}
	UIBgElevated      = Color{Light: "#FFFFFF", Dark: "#1C1C1E"}
	UIBgGrouped       = Color{Light: "#F5F5F7", Dark: "#111113"}
	UIFill1           = Color{Light: "rgba(120, 120, 128, 0.08)", Dark: "rgba(120, 120, 128, 0.16)"}
	UIFill2           = Color{Light: "rgba(120, 120, 128, 0.12)", Dark: "rgba(120, 120, 128, 0.24)"}
	UIFill3           = Color{Light: "rgba(120, 120, 128, 0.16)", Dark: "rgba(120, 120, 128, 0.32)"}
	UISeparator       = Color{Light: "rgba(60, 60, 67, 0.12)", Dark: "rgba(84, 84, 88, 0.48)"}
	UISeparatorStrong = Color{Light: "rgba(60, 60, 67, 0.29)", Dark: "rgba(84, 84, 88, 0.80)"}
	UIMaterial        = Color{Light: "rgba(251, 251, 253, 0.72)", Dark: "rgba(0, 0, 0, 0.68)"}
	UIMaterialSidebar = Color{Light: "rgba(242, 242, 245, 0.78)", Dark: "rgba(28, 28, 30, 0.72)"}
	UILabel1          = Color{Light: "#1D1D1F", Dark: "#F5F5F7"}
	UILabel2          = Color{Light: "#6E6E73", Dark: "#A1A1A6"}
	UILabel3          = Color{Light: "#86868B", Dark: "#8E8E93"}
	UIAccent          = Color{Light: "#4F5BE8", Dark: "#818CF8"}
	UIAccentHover     = Color{Light: "#4350DD", Dark: "#949EFA"}
	UIAccentFill      = Color{Light: "#4F5BE8", Dark: "#5B63E6"}
	UIAccentFillHover = Color{Light: "#4350DD", Dark: "#5058DC"}
	UIOnAccent        = Color{Light: "#FFFFFF", Dark: "#FFFFFF"}
	UIAccentSoft      = Color{Light: "rgba(79, 91, 232, 0.10)", Dark: "rgba(129, 140, 248, 0.18)"}
	UISuccess         = Color{Light: "#1A7F37", Dark: "#30D158"}
	UISuccessSoft     = Color{Light: "rgba(26, 127, 55, 0.10)", Dark: "rgba(48, 209, 88, 0.16)"}
	UIWarning         = Color{Light: "#B25000", Dark: "#FF9F0A"}
	UIWarningSoft     = Color{Light: "rgba(178, 80, 0, 0.10)", Dark: "rgba(255, 159, 10, 0.16)"}
	UIDanger          = Color{Light: "#D70015", Dark: "#FF453A"}
	UIDangerFill      = Color{Light: "#D70015", Dark: "#E0242F"}
	UIDangerFillHover = Color{Light: "#B8000F", Dark: "#C8102E"}
	UIDangerSoft      = Color{Light: "rgba(215, 0, 21, 0.08)", Dark: "rgba(255, 69, 58, 0.16)"}
	UIOnDanger        = Color{Light: "#FFFFFF", Dark: "#FFFFFF"}
	UIInfo            = Color{Light: "#4F5BE8", Dark: "#818CF8"}
	UIChart1          = Color{Light: "#4F5BE8", Dark: "#818CF8"}
	UIChart2          = Color{Light: "#0891B2", Dark: "#22D3EE"}
	UIChart3          = Color{Light: "#8B5CF6", Dark: "#A78BFA"}
	UIChart4          = Color{Light: "#DB2777", Dark: "#F472B6"}
	UIChart5          = Color{Light: "#EA580C", Dark: "#FB923C"}
	UIChart6          = Color{Light: "#A16207", Dark: "#FACC15"}
	UIChart7          = Color{Light: "#16A34A", Dark: "#4ADE80"}
	UIChart8          = Color{Light: "#8E8E93", Dark: "#8E8E93"}
	UIShadowColor     = Color{Light: "rgba(0, 0, 0, 0.06)", Dark: "rgba(0, 0, 0, 0.40)"}
	UIHighlight       = Color{Light: "rgba(255, 255, 255, 0)", Dark: "rgba(255, 255, 255, 0.06)"}
)

// Brand colours (theme independent).
const (
	BrandGradientStart = "#38BDF8"
	BrandGradientEnd   = "#6366F1"
	BrandPurple        = "#8B5CF6"
	BrandAmber         = "#F59E0B"
	BrandSlate900      = "#0F172A"
	BrandSlate800      = "#1E293B"
)

// Terminal palette for CLIs and TUIs.
var (
	TermAccent     = TermColor{Light: "#4F5BE8", Dark: "#818CF8", ANSI256Light: 62, ANSI256Dark: 105, ANSI16: 4}
	TermSuccess    = TermColor{Light: "#1A7F37", Dark: "#30D158", ANSI256Light: 29, ANSI256Dark: 41, ANSI16: 2}
	TermWarning    = TermColor{Light: "#B25000", Dark: "#FF9F0A", ANSI256Light: 130, ANSI256Dark: 214, ANSI16: 3}
	TermDanger     = TermColor{Light: "#D70015", Dark: "#FF453A", ANSI256Light: 160, ANSI256Dark: 203, ANSI16: 1}
	TermMuted      = TermColor{Light: "#6E6E73", Dark: "#8E8E93", ANSI256Light: 242, ANSI256Dark: 246, ANSI16: 8}
	TermBrandStart = TermColor{Light: "#38BDF8", Dark: "#38BDF8", ANSI256Light: 75, ANSI256Dark: 75, ANSI16: 6}
	TermBrandEnd   = TermColor{Light: "#6366F1", Dark: "#6366F1", ANSI256Light: 63, ANSI256Dark: 63, ANSI16: 5}
)

// ASCIIMark is the three-line ASCII mark used in banners and --version output.
var ASCIIMark = [...]string{
	"  ___",
	" / o \\",
	" \\___/",
}
