// Generated by scripts/build-tokens.py from tokens/tokens.json. Do not edit. AnixOps Design 1.0.0.
//
// Usage:
//   MaterialApp(theme: anixOpsTheme(Brightness.light), darkTheme: anixOpsTheme(Brightness.dark))
//   final c = Theme.of(context).extension<AnixOpsColors>()!;  // c.label2, c.success, ...
//
// Inter is not bundled here: add fonts/inter (or google_fonts) to pubspec.yaml, or pass
// fontFamily: null to use the platform font.

// ignore_for_file: constant_identifier_names, non_constant_identifier_names
import 'package:flutter/material.dart';

/// AnixOps colour tokens for one theme. Read with
/// `Theme.of(context).extension<AnixOpsColors>()!`.
@immutable
class AnixOpsColors extends ThemeExtension<AnixOpsColors> {
  const AnixOpsColors({
    required this.bg,
    required this.bgElevated,
    required this.bgGrouped,
    required this.fill1,
    required this.fill2,
    required this.fill3,
    required this.separator,
    required this.separatorStrong,
    required this.material,
    required this.materialSidebar,
    required this.label1,
    required this.label2,
    required this.label3,
    required this.accent,
    required this.accentHover,
    required this.accentFill,
    required this.accentFillHover,
    required this.onAccent,
    required this.accentSoft,
    required this.success,
    required this.successSoft,
    required this.warning,
    required this.warningSoft,
    required this.danger,
    required this.dangerFill,
    required this.dangerFillHover,
    required this.dangerSoft,
    required this.onDanger,
    required this.info,
    required this.chart1,
    required this.chart2,
    required this.chart3,
    required this.chart4,
    required this.chart5,
    required this.chart6,
    required this.chart7,
    required this.chart8,
    required this.shadowColor,
    required this.highlight,
  });

  final Color bg;
  final Color bgElevated;
  final Color bgGrouped;
  final Color fill1;
  final Color fill2;
  final Color fill3;
  final Color separator;
  final Color separatorStrong;
  final Color material;
  final Color materialSidebar;
  final Color label1;
  final Color label2;
  final Color label3;
  final Color accent;
  final Color accentHover;
  final Color accentFill;
  final Color accentFillHover;
  final Color onAccent;
  final Color accentSoft;
  final Color success;
  final Color successSoft;
  final Color warning;
  final Color warningSoft;
  final Color danger;
  final Color dangerFill;
  final Color dangerFillHover;
  final Color dangerSoft;
  final Color onDanger;
  final Color info;
  final Color chart1;
  final Color chart2;
  final Color chart3;
  final Color chart4;
  final Color chart5;
  final Color chart6;
  final Color chart7;
  final Color chart8;
  final Color shadowColor;
  final Color highlight;

  static const light = AnixOpsColors(
    bg: Color(0xFFFBFBFD),
    bgElevated: Color(0xFFFFFFFF),
    bgGrouped: Color(0xFFF5F5F7),
    fill1: Color(0x14787880),
    fill2: Color(0x1F787880),
    fill3: Color(0x29787880),
    separator: Color(0x1F3C3C43),
    separatorStrong: Color(0x4A3C3C43),
    material: Color(0xB8FBFBFD),
    materialSidebar: Color(0xC7F2F2F5),
    label1: Color(0xFF1D1D1F),
    label2: Color(0xFF6E6E73),
    label3: Color(0xFF86868B),
    accent: Color(0xFF4F5BE8),
    accentHover: Color(0xFF4350DD),
    accentFill: Color(0xFF4F5BE8),
    accentFillHover: Color(0xFF4350DD),
    onAccent: Color(0xFFFFFFFF),
    accentSoft: Color(0x1A4F5BE8),
    success: Color(0xFF1A7F37),
    successSoft: Color(0x1A1A7F37),
    warning: Color(0xFFB25000),
    warningSoft: Color(0x1AB25000),
    danger: Color(0xFFD70015),
    dangerFill: Color(0xFFD70015),
    dangerFillHover: Color(0xFFB8000F),
    dangerSoft: Color(0x14D70015),
    onDanger: Color(0xFFFFFFFF),
    info: Color(0xFF4F5BE8),
    chart1: Color(0xFF4F5BE8),
    chart2: Color(0xFF0891B2),
    chart3: Color(0xFF8B5CF6),
    chart4: Color(0xFFDB2777),
    chart5: Color(0xFFEA580C),
    chart6: Color(0xFFA16207),
    chart7: Color(0xFF16A34A),
    chart8: Color(0xFF8E8E93),
    shadowColor: Color(0x0F000000),
    highlight: Color(0x00FFFFFF),
  );

  static const dark = AnixOpsColors(
    bg: Color(0xFF000000),
    bgElevated: Color(0xFF1C1C1E),
    bgGrouped: Color(0xFF111113),
    fill1: Color(0x29787880),
    fill2: Color(0x3D787880),
    fill3: Color(0x52787880),
    separator: Color(0x7A545458),
    separatorStrong: Color(0xCC545458),
    material: Color(0xAD000000),
    materialSidebar: Color(0xB81C1C1E),
    label1: Color(0xFFF5F5F7),
    label2: Color(0xFFA1A1A6),
    label3: Color(0xFF8E8E93),
    accent: Color(0xFF818CF8),
    accentHover: Color(0xFF949EFA),
    accentFill: Color(0xFF5B63E6),
    accentFillHover: Color(0xFF5058DC),
    onAccent: Color(0xFFFFFFFF),
    accentSoft: Color(0x2E818CF8),
    success: Color(0xFF30D158),
    successSoft: Color(0x2930D158),
    warning: Color(0xFFFF9F0A),
    warningSoft: Color(0x29FF9F0A),
    danger: Color(0xFFFF453A),
    dangerFill: Color(0xFFE0242F),
    dangerFillHover: Color(0xFFC8102E),
    dangerSoft: Color(0x29FF453A),
    onDanger: Color(0xFFFFFFFF),
    info: Color(0xFF818CF8),
    chart1: Color(0xFF818CF8),
    chart2: Color(0xFF22D3EE),
    chart3: Color(0xFFA78BFA),
    chart4: Color(0xFFF472B6),
    chart5: Color(0xFFFB923C),
    chart6: Color(0xFFFACC15),
    chart7: Color(0xFF4ADE80),
    chart8: Color(0xFF8E8E93),
    shadowColor: Color(0x66000000),
    highlight: Color(0x0FFFFFFF),
  );

  @override
  AnixOpsColors copyWith({Color? bg, Color? bgElevated, Color? bgGrouped, Color? fill1, Color? fill2, Color? fill3, Color? separator, Color? separatorStrong, Color? material, Color? materialSidebar, Color? label1, Color? label2, Color? label3, Color? accent, Color? accentHover, Color? accentFill, Color? accentFillHover, Color? onAccent, Color? accentSoft, Color? success, Color? successSoft, Color? warning, Color? warningSoft, Color? danger, Color? dangerFill, Color? dangerFillHover, Color? dangerSoft, Color? onDanger, Color? info, Color? chart1, Color? chart2, Color? chart3, Color? chart4, Color? chart5, Color? chart6, Color? chart7, Color? chart8, Color? shadowColor, Color? highlight}) {
    return AnixOpsColors(
      bg: bg ?? this.bg,
      bgElevated: bgElevated ?? this.bgElevated,
      bgGrouped: bgGrouped ?? this.bgGrouped,
      fill1: fill1 ?? this.fill1,
      fill2: fill2 ?? this.fill2,
      fill3: fill3 ?? this.fill3,
      separator: separator ?? this.separator,
      separatorStrong: separatorStrong ?? this.separatorStrong,
      material: material ?? this.material,
      materialSidebar: materialSidebar ?? this.materialSidebar,
      label1: label1 ?? this.label1,
      label2: label2 ?? this.label2,
      label3: label3 ?? this.label3,
      accent: accent ?? this.accent,
      accentHover: accentHover ?? this.accentHover,
      accentFill: accentFill ?? this.accentFill,
      accentFillHover: accentFillHover ?? this.accentFillHover,
      onAccent: onAccent ?? this.onAccent,
      accentSoft: accentSoft ?? this.accentSoft,
      success: success ?? this.success,
      successSoft: successSoft ?? this.successSoft,
      warning: warning ?? this.warning,
      warningSoft: warningSoft ?? this.warningSoft,
      danger: danger ?? this.danger,
      dangerFill: dangerFill ?? this.dangerFill,
      dangerFillHover: dangerFillHover ?? this.dangerFillHover,
      dangerSoft: dangerSoft ?? this.dangerSoft,
      onDanger: onDanger ?? this.onDanger,
      info: info ?? this.info,
      chart1: chart1 ?? this.chart1,
      chart2: chart2 ?? this.chart2,
      chart3: chart3 ?? this.chart3,
      chart4: chart4 ?? this.chart4,
      chart5: chart5 ?? this.chart5,
      chart6: chart6 ?? this.chart6,
      chart7: chart7 ?? this.chart7,
      chart8: chart8 ?? this.chart8,
      shadowColor: shadowColor ?? this.shadowColor,
      highlight: highlight ?? this.highlight,
    );
  }

  @override
  AnixOpsColors lerp(ThemeExtension<AnixOpsColors>? other, double t) {
    if (other is! AnixOpsColors) return this;
    return AnixOpsColors(
      bg: Color.lerp(bg, other.bg, t)!,
      bgElevated: Color.lerp(bgElevated, other.bgElevated, t)!,
      bgGrouped: Color.lerp(bgGrouped, other.bgGrouped, t)!,
      fill1: Color.lerp(fill1, other.fill1, t)!,
      fill2: Color.lerp(fill2, other.fill2, t)!,
      fill3: Color.lerp(fill3, other.fill3, t)!,
      separator: Color.lerp(separator, other.separator, t)!,
      separatorStrong: Color.lerp(separatorStrong, other.separatorStrong, t)!,
      material: Color.lerp(material, other.material, t)!,
      materialSidebar: Color.lerp(materialSidebar, other.materialSidebar, t)!,
      label1: Color.lerp(label1, other.label1, t)!,
      label2: Color.lerp(label2, other.label2, t)!,
      label3: Color.lerp(label3, other.label3, t)!,
      accent: Color.lerp(accent, other.accent, t)!,
      accentHover: Color.lerp(accentHover, other.accentHover, t)!,
      accentFill: Color.lerp(accentFill, other.accentFill, t)!,
      accentFillHover: Color.lerp(accentFillHover, other.accentFillHover, t)!,
      onAccent: Color.lerp(onAccent, other.onAccent, t)!,
      accentSoft: Color.lerp(accentSoft, other.accentSoft, t)!,
      success: Color.lerp(success, other.success, t)!,
      successSoft: Color.lerp(successSoft, other.successSoft, t)!,
      warning: Color.lerp(warning, other.warning, t)!,
      warningSoft: Color.lerp(warningSoft, other.warningSoft, t)!,
      danger: Color.lerp(danger, other.danger, t)!,
      dangerFill: Color.lerp(dangerFill, other.dangerFill, t)!,
      dangerFillHover: Color.lerp(dangerFillHover, other.dangerFillHover, t)!,
      dangerSoft: Color.lerp(dangerSoft, other.dangerSoft, t)!,
      onDanger: Color.lerp(onDanger, other.onDanger, t)!,
      info: Color.lerp(info, other.info, t)!,
      chart1: Color.lerp(chart1, other.chart1, t)!,
      chart2: Color.lerp(chart2, other.chart2, t)!,
      chart3: Color.lerp(chart3, other.chart3, t)!,
      chart4: Color.lerp(chart4, other.chart4, t)!,
      chart5: Color.lerp(chart5, other.chart5, t)!,
      chart6: Color.lerp(chart6, other.chart6, t)!,
      chart7: Color.lerp(chart7, other.chart7, t)!,
      chart8: Color.lerp(chart8, other.chart8, t)!,
      shadowColor: Color.lerp(shadowColor, other.shadowColor, t)!,
      highlight: Color.lerp(highlight, other.highlight, t)!,
    );
  }
}

/// Brand colours. The gradient is for brand moments only (logo tile, login, hero).
abstract final class AnixOpsBrand {
  static const gradientStart = Color(0xFF38BDF8);
  static const gradientEnd = Color(0xFF6366F1);
  static const purple = Color(0xFF8B5CF6);
  static const amber = Color(0xFFF59E0B);
  static const slate900 = Color(0xFF0F172A);
  static const slate800 = Color(0xFF1E293B);
  static const gradient = LinearGradient(
    begin: Alignment.topLeft,
    end: Alignment.bottomRight,
    colors: [gradientStart, gradientEnd],
  );
}

abstract final class AnixOpsSpace {
  static const double s0_5 = 2;
  static const double s1 = 4;
  static const double s2 = 8;
  static const double s3 = 12;
  static const double s4 = 16;
  static const double s5 = 20;
  static const double s6 = 24;
  static const double s8 = 32;
  static const double s10 = 40;
  static const double s12 = 48;
  static const double s16 = 64;
  static const double s20 = 80;
}

abstract final class AnixOpsRadius {
  static const double xs = 6;
  static const double sm = 10;
  static const double md = 14;
  static const double lg = 20;
  static const double pill = 980;
}

abstract final class AnixOpsSize {
  static const double controlLg = 44;
  static const double controlMd = 36;
  static const double controlSm = 28;
  static const double contentUser = 980;
  static const double contentAdmin = 1280;
  static const double contentWide = 1440;
  static const double contentRead = 692;
}

abstract final class AnixOpsMotion {
  static const micro = Duration(milliseconds: 120);
  static const toggle = Duration(milliseconds: 200);
  static const overlay = Duration(milliseconds: 280);
  static const page = Duration(milliseconds: 240);
  static const standard = Cubic(0.25, 0.1, 0.25, 1);
  static const emphasized = Cubic(0.2, 0.8, 0.2, 1);
  static const exit = Cubic(0.4, 0, 1, 1);
}

/// The seven-step type scale. Colours come from the theme.
abstract final class AnixOpsType {
  static const display = TextStyle(fontSize: 48, height: 1.08, fontWeight: FontWeight.w700, letterSpacing: -0.72);
  static const title1 = TextStyle(fontSize: 32, height: 1.125, fontWeight: FontWeight.w700, letterSpacing: -0.32);
  static const title2 = TextStyle(fontSize: 24, height: 1.17, fontWeight: FontWeight.w600, letterSpacing: -0.12);
  static const title3 = TextStyle(fontSize: 19, height: 1.26, fontWeight: FontWeight.w600, letterSpacing: 0);
  static const body = TextStyle(fontSize: 15, height: 1.47, fontWeight: FontWeight.w400, letterSpacing: 0);
  static const callout = TextStyle(fontSize: 13, height: 1.38, fontWeight: FontWeight.w400, letterSpacing: 0);
  static const caption = TextStyle(fontSize: 12, height: 1.33, fontWeight: FontWeight.w500, letterSpacing: 0);
}

/// Material 3 theme built from the tokens.
ThemeData anixOpsTheme(Brightness brightness, {String? fontFamily = 'Inter'}) {
  final c = brightness == Brightness.dark ? AnixOpsColors.dark : AnixOpsColors.light;
  final scheme = ColorScheme(
    brightness: brightness,
    primary: c.accentFill,
    onPrimary: c.onAccent,
    secondary: c.accentFill,
    onSecondary: c.onAccent,
    error: c.dangerFill,
    onError: c.onDanger,
    surface: c.bgElevated,
    onSurface: c.label1,
    onSurfaceVariant: c.label2,
    outline: c.separatorStrong,
    outlineVariant: c.separator,
  );
  const textTheme = TextTheme(
    displayLarge: AnixOpsType.display,
    headlineLarge: AnixOpsType.title1,
    headlineMedium: AnixOpsType.title2,
    titleLarge: AnixOpsType.title3,
    titleMedium: AnixOpsType.body,
    bodyLarge: AnixOpsType.body,
    bodyMedium: AnixOpsType.body,
    bodySmall: AnixOpsType.callout,
    labelLarge: AnixOpsType.callout,
    labelMedium: AnixOpsType.caption,
    labelSmall: AnixOpsType.caption,
  );
  return ThemeData(
    useMaterial3: true,
    brightness: brightness,
    colorScheme: scheme,
    scaffoldBackgroundColor: c.bg,
    dividerColor: c.separator,
    fontFamily: fontFamily,
    fontFamilyFallback: const ['PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei', 'Noto Sans SC'],
    textTheme: textTheme.apply(bodyColor: c.label1, displayColor: c.label1),
    extensions: [c],
  );
}
